name: Build

on:
  create: { }
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run build process
        run: sudo bash build_host.sh
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: usb.img.gz
          path: ./usb.img.gz
      - name: Release build artifacts
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./usb.img.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
